source "https://github.com/guotong314/podSpec.git"
source "https://github.com/CocoaPods/Specs.git"
platform :ios, '7.0'

target 'GTI8Login_Example' do
#  pod 'GTI8Login', :path => '../'

pod 'GTSpec'
pod 'GTUser'
pod 'GTNetWork'
pod 'GTRootKit'

  target 'GTI8Login_Tests' do
    inherit! :search_paths

    
  end
end
